Workflow model
MastodonC/witan.models.household pull request #1
Opened 2016-09-19 17:46 UTC by Eleonore9

Try and start the household model by creating a workflow and workspace using witan.workspace-api

2016-09-27 13:29 UTC, acron0 requested changes
https://github.com/MastodonC/witan.models.demography/blob/master/test/witan/models/acceptance/workspace_test.clj

I think you should change the test to use the style above, rather than the 'run-models' style (`tasks` map and `make-*` functions) as it's way more accurate and less maintainance.

2016-09-27 13:29 UTC, acron0 commented on project.clj
> +                 [witan.workspace-executor "0.2.6"
Put the executor in a test/dev profile so it's only required when running tests.

2016-09-28 15:41 UTC, sunnytownsend reviewed
Remove 'Try and' from beginning of comment - you totally are starting the model!

2016-09-28 15:41 UTC, sunnytownsend commented on test/witan/models/household_test.clj
> +               (set model-ns-fns)))))))
This is the test I remember @acron0 wrote to validate the model - could you run this test also? https://github.com/MastodonC/witan.models.demography/blob/master/test/witan/models/dem/ccm/models_test.clj#L15

2016-09-28 15:47 UTC, sunnytownsend reviewed
Your question: -> is the workflow correct (compared to the diagram)? 

You could run the graph viz on the workflow and compare against your flowchart

2016-09-28 15:47 UTC, Eleonore9 commented on test/witan/models/household_test.clj
> +               (set model-ns-fns)))))))
Ok :ok_hand: there are two extra tests here. I'll add them, now!

2016-09-28 15:49 UTC, sunnytownsend commented on src/witan/models/household.clj
> +(defworkflowfn gather-outputs-1-0-0
Gather has a specific data munging meaning, so please could you change the word `gather` to `collate` or something like that.

2016-09-28 15:52 UTC, sunnytownsend commented on src/witan/models/model.clj
> +   [:input-resident-popn :calculate-household-popn]
I would suggest editing the words in the flowchart to match the code - so the docs are as clear as poss

2016-09-28 15:56 UTC, sunnytownsend commented on src/witan/models/model.clj
> +   [:input-household-rates :calculate-households]
I know its a bit anal and makes the fn longer, but there may be different kinds of household rates so could you change `input-household-rates` to `input-household-representative-rates`

2016-09-28 15:58 UTC, sunnytownsend commented on src/witan/models/model.clj
> +   [:calculate-total-households :gather-outputs]
I guess you should probably add this to your flowchart at least temporarily

2016-09-28 16:42 UTC, Eleonore9 commented on test/witan/models/household_test.clj
> +               (set model-ns-fns)))))))
That's done now!

2016-09-28 16:54 UTC, Eleonore9 commented on src/witan/models/household.clj
> +(defworkflowfn gather-outputs-1-0-0
Done!

2016-09-28 17:00 UTC, Eleonore9 commented on src/witan/models/model.clj
> +   [:input-household-rates :calculate-households]
Done!

2016-09-28 17:19 UTC, Eleonore9 commented
New diagram closer to the workflow (in progress): https://docs.google.com/drawings/d/1q_B3zG2EUIIlyREkIjplq5vmiY5U3KUnp-lHtqkExpE/edit

2016-09-29 09:18 UTC, Eleonore9 commented on project.clj
> +                 [witan.workspace-executor "0.2.6"
Done

2016-09-29 09:24 UTC, Eleonore9 commented on src/witan/models/model.clj
> +   [:calculate-total-households :gather-outputs]
I added all the steps to a copy of the flowchart

2016-09-29 09:32 UTC, Eleonore9 commented on src/witan/models/model.clj
> +   [:input-resident-popn :calculate-household-popn]
Done

2016-09-29 15:07 UTC, sunnytownsend commented
excellent stuff! :shipit:

2016-09-29 15:09 UTC, merged