WIP: Check the sensibility of the results
MastodonC/witan.models.household pull request #11
Opened 2016-11-03 18:31 UTC by Eleonore9

2016-11-07 10:37 UTC, acron0 requested changes

2016-11-07 10:37 UTC, acron0 commented on test/witan/models/soak_test.clj
> +(defn- load-csv
This fn appears in more than one place - is it able to be moved to another location?

EDIT: Looks this this is true of a few  of the other fns in this file

2016-11-07 10:37 UTC, acron0 commented on test/witan/models/soak_test.clj
> +#_(deftest all-local-authorities-test
It'd be good if you could toggle this test on with the presence of an environmental var, then we can have it run on Circle CI - but I understand not wanting to run it locally every time, if it takes 18 mins

2016-11-07 10:46 UTC, Eleonore9 commented on test/witan/models/soak_test.clj
> +(defn- load-csv
You tend not to recommend defining a set of helper fns in a `utils.clj` file.
That'd be only alternative I'd think of here!

2016-11-07 13:37 UTC, sunnytownsend commented on test/witan/models/soak_test.clj
> +  { :population [(with-gss "./data/default_datasets/population/ons_2014_based_snpp" gss-code)
white space

2016-11-07 13:37 UTC, sunnytownsend commented on test/witan/models/soak_test.clj
> +  { :population [(with-gss "./data/default_datasets/population/ons_2014_based_snpp" gss-code)
Have you run eastwood etc?

2016-11-07 13:38 UTC, sunnytownsend commented
have you run eastwood etc?

2016-11-07 13:46 UTC, sunnytownsend commented
great job Eleonore here is your model review :shipit:

2016-11-07 14:46 UTC, Eleonore9 commented
Ran `lein eastwood` and `lein kibit` -> no changes
Ran `lein cljfmt check/fix` -> formatted several namespaces

2016-11-09 10:01 UTC, acron0 submitted a review, later dismissed

2016-11-09 10:01 UTC, acron0 commented on project.clj
> +                 [environ "1.0.1"]]
Could you move this into the dev dependencies?

2016-11-09 12:03 UTC, merged