Feature/add calcs
MastodonC/witan.models.household pull request #4
Opened 2016-10-05 16:19 UTC by Eleonore9

Fill in the workflowfns
-> add testing datasets
-> add schemas

2016-10-05 16:34 UTC, Eleonore9 commented
:( will look at my tests tomorrow! They seem to pass locally... To investigate

2016-10-06 10:52 UTC, Eleonore9 commented
Ok, that's normal. The `household-workspace-test` will fail until I add all the calculations.

2016-10-10 08:32 UTC, acron0 requested changes

2016-10-10 08:32 UTC, acron0 commented on resources/testing_data.edn
> +{:test-inputs
Could this file be a separate resources dir which is referenced in the `dev` profile? Otherwise this will be included in the JAR.

2016-10-10 08:32 UTC, acron0 commented on src/witan/models/household.clj
> +  (let [joined-popns (wds/join resident-popn institutional-popn
This `let` can be `thread-first`d (`->`)

2016-10-10 08:32 UTC, acron0 commented on src/witan/models/household.clj
> +  (let [popn-with-grp-col (wds/add-derived-column household-popn :age-group
Thread first again

2016-10-10 08:32 UTC, acron0 commented on src/witan/models/household.clj
> +                                                  (fn [a] (u/get-age-grp a)))
Don't need the surrounding `fn` part, just use `u/get-age-grp`

2016-10-10 08:32 UTC, acron0 commented on src/witan/models/household.clj
> +  (let [joined-ds (wds/join household-representative-rates household-popn-grp
Thread first again

2016-10-10 08:32 UTC, acron0 commented on src/witan/models/household.clj
> +  (let [joined-ds (wds/join vacancy-rates second-homes-rates [:gss-code :year])
Thread first :)

2016-10-10 08:32 UTC, acron0 commented on src/witan/models/household.clj
> +                                               (fn [hh or] (* hh (- 1 or))))
`or` is a bad name for a value because it conflicts with `clojure.core/or` -> you can suffix with `'` (e.g. `or'` if you really want to use that initialisation). Also, `(- 1 or)` (i.e. `1 - or`) is definitely what you want here?

2016-10-10 08:32 UTC, acron0 commented on src/witan/models/household.clj
> +  (let [joined-ds (wds/join total-households occupancy-rates [:gss-code :year])
Thread first

2016-10-10 11:41 UTC, Eleonore9 commented on src/witan/models/household.clj
> +                                               (fn [hh or] (* hh (- 1 or))))
Oh thanks. I just went for `or` bc it stands for "occupancy rates".
Yes, what I went is `housholds * (1 - occupancy-rates)`

2016-10-10 11:50 UTC, acron0 approved these changes

2016-10-10 12:23 UTC, sunnytownsend commented
General question - can you remind me why do we use edn files?

2016-10-10 12:25 UTC, sunnytownsend commented on data/testing_data.edn
> + :test-outputs
where did you get these from?

2016-10-10 12:53 UTC, Eleonore9 commented on data/testing_data.edn
> + :test-outputs
They're all fake data

2016-10-10 12:54 UTC, Eleonore9 commented
Edn files are easy to read in as Clojure data structure.
In this case, it's temporary. Until I get "real" data.

2016-10-10 13:03 UTC, sunnytownsend commented
we discussed that in the next branch, the fake data would be replaced with extracts of real data from Pier's model to test the functions we are implementing are doing what he intended. For this PR though - lgtm :shipit:

2016-10-10 13:11 UTC, merged